
package apu.medical.centre;
import java.text.SimpleDateFormat;
import javax.swing.*;

public class Customer extends javax.swing.JFrame {
    private String username,role,password,fullname,id;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer.class.getName());
    private User customer;
//    private Individual in = new Individual();
    private final CustomerClass customerService;

    public Customer(User customer) {
        initComponents();
        setLocationRelativeTo(null);
        this.customer = customer;
        setupInitialView();
        this.setTitle("APU Medical Center (Customer)");
        this.setFocusableWindowState(true);
        this.setAutoRequestFocus(true);
        this.customerService = new CustomerClass(customer);
        loadUserProfile();
        CustomerClass.dateChooser(appointmemtDateChooser);
    }
    
    private void setupInitialView() {
        this.remove(viewHistoryPanel);
        this.remove(viewAppointmentPanel);
        this.remove(submitCommentPanel);
        this.remove(viewProfilePanel);
        this.remove(editProfilePanel);
        profileButton.setText(customer.getFullName());
        headerlabel.setText("Hi, " + customer.getUsername());
    }
    
    private void loadUserProfile() {
        iduserLabel.setText(customer.getId());
        nameuserLabel.setText(customer.getUsername());
        fullnameuserLabel.setText(customer.getFullName());
        roleuserLabel.setText(customer.getRole());
        passworduserLabel.setText("*****");
        useridLabel.setText(customer.getId());
        userroleLabel.setText(customer.getRole());
        userfullnameLabel.setText(customer.getFullName());
    }
    
     
    private void switchPanel(javax.swing.JPanel targetPanel, String headerText) {
        this.remove(customerPanel);
        this.remove(viewHistoryPanel);
        this.remove(viewAppointmentPanel);
        this.remove(submitCommentPanel);
        this.remove(viewProfilePanel);
        this.remove(editProfilePanel);
        this.revalidate();
        this.repaint();
        this.add(targetPanel);
        headerlabel.setText(headerText);
        targetPanel.requestFocusInWindow();
        if (targetPanel == editProfilePanel) {
            newnameTextfield.requestFocusInWindow();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewHistoryPanel = new javax.swing.JPanel();
        historyScrollPanel = new javax.swing.JScrollPane();
        completeTable = new javax.swing.JTable();
        refreshhistoryButton = new javax.swing.JButton();
        showhistoryButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        headerlabel = new javax.swing.JLabel();
        customerPanel = new javax.swing.JPanel();
        viewappointmentButton = new javax.swing.JButton();
        submitcommentButton = new javax.swing.JButton();
        viewhistoryButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        viewAppointmentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewappointmentTable = new javax.swing.JTable();
        rescheduleappointmentButton = new javax.swing.JButton();
        cancelappointmentButton = new javax.swing.JButton();
        timeComboBox = new javax.swing.JComboBox<>();
        appointmemtDateChooser = new com.toedter.calendar.JDateChooser();
        dateLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        submitCommentPanel = new javax.swing.JPanel();
        ccdLabel = new javax.swing.JLabel();
        ccsLabel = new javax.swing.JLabel();
        doctorTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        feedbackTable = new javax.swing.JTable();
        staffTextField = new javax.swing.JTextField();
        viewProfilePanel = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        rolelabel = new javax.swing.JLabel();
        editprofileButton = new javax.swing.JButton();
        idlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        fullnamelabel = new javax.swing.JLabel();
        iduserLabel = new javax.swing.JLabel();
        fullnameuserLabel = new javax.swing.JLabel();
        roleuserLabel = new javax.swing.JLabel();
        nameuserLabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        passworduserLabel = new javax.swing.JLabel();
        editProfilePanel = new javax.swing.JPanel();
        epButton = new javax.swing.JButton();
        useridLabel = new javax.swing.JLabel();
        userroleLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        roleLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        newpasswordLabel = new javax.swing.JLabel();
        newnameLabel = new javax.swing.JLabel();
        fullnameLabel = new javax.swing.JLabel();
        userfullnameLabel = new javax.swing.JLabel();
        newnameTextfield = new javax.swing.JTextField();
        newpasswordTextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 255, 255));
        setFocusableWindowState(false);
        setForeground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        viewHistoryPanel.setBackground(new java.awt.Color(204, 255, 255));
        viewHistoryPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        viewHistoryPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        completeTable.setBackground(new java.awt.Color(153, 255, 255));
        completeTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        completeTable.setForeground(new java.awt.Color(51, 51, 255));
        completeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        completeTable.setGridColor(new java.awt.Color(0, 0, 153));
        completeTable.setRowHeight(25);
        completeTable.setSelectionBackground(new java.awt.Color(153, 204, 255));
        historyScrollPanel.setViewportView(completeTable);

        refreshhistoryButton.setBackground(new java.awt.Color(255, 255, 255));
        refreshhistoryButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        refreshhistoryButton.setForeground(new java.awt.Color(51, 51, 255));
        refreshhistoryButton.setText("Refresh");
        refreshhistoryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        refreshhistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshhistoryButtonActionPerformed(evt);
            }
        });

        showhistoryButton.setBackground(new java.awt.Color(255, 255, 255));
        showhistoryButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        showhistoryButton.setForeground(new java.awt.Color(51, 51, 255));
        showhistoryButton.setText("Show");
        showhistoryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        showhistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showhistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewHistoryPanelLayout = new javax.swing.GroupLayout(viewHistoryPanel);
        viewHistoryPanel.setLayout(viewHistoryPanelLayout);
        viewHistoryPanelLayout.setHorizontalGroup(
            viewHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewHistoryPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(viewHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewHistoryPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(refreshhistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showhistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addComponent(historyScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        viewHistoryPanelLayout.setVerticalGroup(
            viewHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewHistoryPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(historyScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshhistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showhistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(0, 153, 255));
        headerPanel.setPreferredSize(new java.awt.Dimension(900, 40));

        homeButton.setBackground(new java.awt.Color(0, 153, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(0, 153, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        headerlabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        headerlabel.setForeground(new java.awt.Color(255, 255, 255));
        headerlabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 551, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        customerPanel.setBackground(new java.awt.Color(204, 255, 255));
        customerPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        customerPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        viewappointmentButton.setBackground(new java.awt.Color(255, 255, 255));
        viewappointmentButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        viewappointmentButton.setForeground(new java.awt.Color(51, 51, 255));
        viewappointmentButton.setText("View Appointment");
        viewappointmentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        viewappointmentButton.setMaximumSize(new java.awt.Dimension(164, 23));
        viewappointmentButton.setMinimumSize(new java.awt.Dimension(164, 23));
        viewappointmentButton.setPreferredSize(new java.awt.Dimension(164, 23));
        viewappointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewappointmentButtonActionPerformed(evt);
            }
        });

        submitcommentButton.setBackground(new java.awt.Color(255, 255, 255));
        submitcommentButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        submitcommentButton.setForeground(new java.awt.Color(51, 51, 255));
        submitcommentButton.setText("Submit Comment");
        submitcommentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        submitcommentButton.setMaximumSize(new java.awt.Dimension(164, 23));
        submitcommentButton.setMinimumSize(new java.awt.Dimension(164, 23));
        submitcommentButton.setPreferredSize(new java.awt.Dimension(164, 23));
        submitcommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitcommentButtonActionPerformed(evt);
            }
        });

        viewhistoryButton.setBackground(new java.awt.Color(255, 255, 255));
        viewhistoryButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        viewhistoryButton.setForeground(new java.awt.Color(51, 51, 255));
        viewhistoryButton.setText("View History");
        viewhistoryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        viewhistoryButton.setMaximumSize(new java.awt.Dimension(200, 25));
        viewhistoryButton.setMinimumSize(new java.awt.Dimension(200, 25));
        viewhistoryButton.setPreferredSize(new java.awt.Dimension(200, 25));
        viewhistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewhistoryButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(204, 255, 255));
        profileButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        profileButton.setForeground(new java.awt.Color(51, 51, 255));
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilepic.png"))); // NOI18N
        profileButton.setText("    Hi!");
        profileButton.setBorder(null);
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitcommentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewhistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewappointmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewhistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewappointmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(submitcommentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        viewAppointmentPanel.setBackground(new java.awt.Color(204, 255, 255));
        viewAppointmentPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        viewappointmentTable.setBackground(new java.awt.Color(153, 255, 255));
        viewappointmentTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        viewappointmentTable.setForeground(new java.awt.Color(51, 51, 255));
        viewappointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewappointmentTable.setGridColor(new java.awt.Color(0, 0, 153));
        viewappointmentTable.setRowHeight(25);
        viewappointmentTable.setSelectionBackground(new java.awt.Color(153, 204, 255));
        viewappointmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewappointmentTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(viewappointmentTable);

        rescheduleappointmentButton.setBackground(new java.awt.Color(255, 255, 255));
        rescheduleappointmentButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rescheduleappointmentButton.setForeground(new java.awt.Color(51, 51, 255));
        rescheduleappointmentButton.setText("Reschedule Appointment");
        rescheduleappointmentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        rescheduleappointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescheduleappointmentButtonActionPerformed(evt);
            }
        });

        cancelappointmentButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelappointmentButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cancelappointmentButton.setForeground(new java.awt.Color(51, 51, 255));
        cancelappointmentButton.setText("Cancel Appointment");
        cancelappointmentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        cancelappointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelappointmentButtonActionPerformed(evt);
            }
        });

        timeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        timeComboBox.setForeground(new java.awt.Color(51, 51, 255));
        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        appointmemtDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        appointmemtDateChooser.setForeground(new java.awt.Color(51, 51, 255));
        appointmemtDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                appointmemtDateChooserPropertyChange(evt);
            }
        });

        dateLable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        dateLable.setForeground(new java.awt.Color(51, 51, 255));
        dateLable.setText("Select Date:");

        timeLable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        timeLable.setForeground(new java.awt.Color(51, 51, 255));
        timeLable.setText("Select Time:");

        javax.swing.GroupLayout viewAppointmentPanelLayout = new javax.swing.GroupLayout(viewAppointmentPanel);
        viewAppointmentPanel.setLayout(viewAppointmentPanelLayout);
        viewAppointmentPanelLayout.setHorizontalGroup(
            viewAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAppointmentPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(dateLable)
                .addGap(31, 31, 31)
                .addComponent(appointmemtDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(timeLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(viewAppointmentPanelLayout.createSequentialGroup()
                .addGroup(viewAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAppointmentPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewAppointmentPanelLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(viewAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelappointmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rescheduleappointmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewAppointmentPanelLayout.setVerticalGroup(
            viewAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAppointmentPanelLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(viewAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAppointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(appointmemtDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(rescheduleappointmentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelappointmentButton)
                .addGap(64, 64, 64))
        );

        submitCommentPanel.setBackground(new java.awt.Color(204, 255, 255));

        ccdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ccdLabel.setForeground(new java.awt.Color(51, 51, 255));
        ccdLabel.setText("Comment to Doctor:");

        ccsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ccsLabel.setForeground(new java.awt.Color(51, 51, 255));
        ccsLabel.setText("Comment to Staff:");

        doctorTextField.setBackground(new java.awt.Color(153, 255, 255));
        doctorTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doctorTextField.setForeground(new java.awt.Color(51, 51, 255));
        doctorTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        doctorTextField.setDragEnabled(true);
        doctorTextField.setFocusCycleRoot(true);
        doctorTextField.setFocusTraversalPolicyProvider(true);

        submitButton.setBackground(new java.awt.Color(255, 255, 255));
        submitButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        submitButton.setForeground(new java.awt.Color(51, 51, 255));
        submitButton.setText("Submit");
        submitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        feedbackTable.setBackground(new java.awt.Color(153, 255, 255));
        feedbackTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        feedbackTable.setForeground(new java.awt.Color(51, 51, 255));
        feedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        feedbackTable.setGridColor(new java.awt.Color(0, 0, 153));
        feedbackTable.setRowHeight(25);
        feedbackTable.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane2.setViewportView(feedbackTable);

        staffTextField.setBackground(new java.awt.Color(102, 255, 255));
        staffTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        staffTextField.setForeground(new java.awt.Color(51, 51, 255));
        staffTextField.setToolTipText("");
        staffTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        staffTextField.setFocusCycleRoot(true);
        staffTextField.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout submitCommentPanelLayout = new javax.swing.GroupLayout(submitCommentPanel);
        submitCommentPanel.setLayout(submitCommentPanelLayout);
        submitCommentPanelLayout.setHorizontalGroup(
            submitCommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitCommentPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(ccsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(submitCommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(submitCommentPanelLayout.createSequentialGroup()
                        .addComponent(staffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(ccdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitCommentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        submitCommentPanelLayout.setVerticalGroup(
            submitCommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitCommentPanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(submitCommentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccsLabel)
                    .addComponent(ccdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(submitButton)
                .addGap(78, 78, 78))
        );

        viewProfilePanel.setBackground(new java.awt.Color(204, 255, 255));

        Button.setBackground(new java.awt.Color(204, 255, 255));
        Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilepic.png"))); // NOI18N
        Button.setBorder(null);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        rolelabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rolelabel.setForeground(new java.awt.Color(51, 51, 255));
        rolelabel.setText("Role:");

        editprofileButton.setBackground(new java.awt.Color(255, 255, 255));
        editprofileButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        editprofileButton.setForeground(new java.awt.Color(51, 51, 255));
        editprofileButton.setText("Edit");
        editprofileButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        editprofileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprofileButtonActionPerformed(evt);
            }
        });

        idlabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        idlabel.setForeground(new java.awt.Color(51, 51, 255));
        idlabel.setText("ID:");

        namelabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        namelabel.setForeground(new java.awt.Color(51, 51, 255));
        namelabel.setText("Name:");

        fullnamelabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        fullnamelabel.setForeground(new java.awt.Color(51, 51, 255));
        fullnamelabel.setText("Full Name:");

        iduserLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        iduserLabel.setForeground(new java.awt.Color(51, 51, 255));

        fullnameuserLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        fullnameuserLabel.setForeground(new java.awt.Color(51, 51, 255));

        roleuserLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        roleuserLabel.setForeground(new java.awt.Color(51, 51, 255));

        nameuserLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nameuserLabel.setForeground(new java.awt.Color(51, 51, 255));

        passwordlabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(51, 51, 255));
        passwordlabel.setText("Password:");

        passworduserLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        passworduserLabel.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout viewProfilePanelLayout = new javax.swing.GroupLayout(viewProfilePanel);
        viewProfilePanel.setLayout(viewProfilePanelLayout);
        viewProfilePanelLayout.setHorizontalGroup(
            viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProfilePanelLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewProfilePanelLayout.createSequentialGroup()
                            .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rolelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fullnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(roleuserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passworduserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fullnameuserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameuserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iduserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewProfilePanelLayout.createSequentialGroup()
                            .addComponent(editprofileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)))
                    .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        viewProfilePanelLayout.setVerticalGroup(
            viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProfilePanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iduserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameuserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullnameuserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleuserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passworduserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editprofileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        editProfilePanel.setBackground(new java.awt.Color(204, 255, 255));
        editProfilePanel.setPreferredSize(new java.awt.Dimension(900, 600));
        editProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        epButton.setBackground(new java.awt.Color(204, 255, 255));
        epButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profilepic.png"))); // NOI18N
        epButton.setBorder(null);
        epButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epButtonActionPerformed(evt);
            }
        });
        editProfilePanel.add(epButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 111, 496, 126));

        useridLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        useridLabel.setForeground(new java.awt.Color(51, 51, 255));
        editProfilePanel.add(useridLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 255, 190, 39));

        userroleLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        userroleLabel.setForeground(new java.awt.Color(51, 51, 255));
        editProfilePanel.add(userroleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 402, 190, 28));

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        saveButton.setForeground(new java.awt.Color(51, 51, 255));
        saveButton.setText("Save");
        saveButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        editProfilePanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 488, 152, 55));

        roleLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(51, 51, 255));
        roleLabel.setText("Role:");
        editProfilePanel.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 402, 93, 28));

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        idLabel.setForeground(new java.awt.Color(51, 51, 255));
        idLabel.setText("ID:");
        editProfilePanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 255, 93, 39));

        newpasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newpasswordLabel.setForeground(new java.awt.Color(51, 51, 255));
        newpasswordLabel.setText("New Password:");
        editProfilePanel.add(newpasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 436, 176, 40));

        newnameLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newnameLabel.setForeground(new java.awt.Color(51, 51, 255));
        newnameLabel.setText("New Name:");
        editProfilePanel.add(newnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 300, 119, 39));

        fullnameLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        fullnameLabel.setForeground(new java.awt.Color(51, 51, 255));
        fullnameLabel.setText("Full Name:");
        editProfilePanel.add(fullnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 357, 119, 39));

        userfullnameLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        userfullnameLabel.setForeground(new java.awt.Color(51, 51, 255));
        editProfilePanel.add(userfullnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 357, 160, 39));

        newnameTextfield.setBackground(new java.awt.Color(153, 255, 255));
        newnameTextfield.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newnameTextfield.setForeground(new java.awt.Color(0, 0, 255));
        newnameTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        newnameTextfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        newnameTextfield.setName(""); // NOI18N
        newnameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newnameTextfieldActionPerformed(evt);
            }
        });
        editProfilePanel.add(newnameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 304, 215, -1));

        newpasswordTextfield.setBackground(new java.awt.Color(153, 255, 255));
        newpasswordTextfield.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newpasswordTextfield.setForeground(new java.awt.Color(0, 0, 255));
        newpasswordTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        newpasswordTextfield.setName(""); // NOI18N
        newpasswordTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordTextfieldActionPerformed(evt);
            }
        });
        editProfilePanel.add(newpasswordTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 441, 213, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewAppointmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(submitCommentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(editProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(viewAppointmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(submitCommentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewProfilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(editProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewappointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewappointmentButtonActionPerformed
        switchPanel(viewAppointmentPanel, "View Appointment");
        initializeDateTimeOptions();
        
        CustomerClass psn = new CustomerClass(customer);
        psn.viewAppointment(viewappointmentTable, customer);
    }//GEN-LAST:event_viewappointmentButtonActionPerformed

    private void submitcommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitcommentButtonActionPerformed
        switchPanel(submitCommentPanel, "Submit Comment");
        customerService.loadFeedbackTable(feedbackTable, customer);
    }//GEN-LAST:event_submitcommentButtonActionPerformed
    
    private void viewhistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewhistoryButtonActionPerformed
        switchPanel(viewHistoryPanel, "View History");
        refreshhistoryButtonActionPerformed(evt);
    }//GEN-LAST:event_viewhistoryButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        switchPanel(viewProfilePanel, "View Profile");
        loadUserProfile();
    }//GEN-LAST:event_profileButtonActionPerformed

    private void refreshhistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshhistoryButtonActionPerformed
        switchPanel(viewHistoryPanel, "View History");
        
        CustomerClass psn = new CustomerClass(customer);
        psn.viewHistory(completeTable, customer);
    }//GEN-LAST:event_refreshhistoryButtonActionPerformed

    private void epButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epButtonActionPerformed
        switchPanel(editProfilePanel, "Edit Profile");
        loadUserProfile();
    }//GEN-LAST:event_epButtonActionPerformed

    private void editprofileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofileButtonActionPerformed
        switchPanel(editProfilePanel, "Edit Profile");
        loadUserProfile();
    }//GEN-LAST:event_editprofileButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        switchPanel(customerPanel, "Hi, " + customer.getUsername());
    }//GEN-LAST:event_homeButtonActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Welcome, " + customer.getFullName() + "!");
    }//GEN-LAST:event_ButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        Login user = new Login();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void cancelappointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelappointmentButtonActionPerformed
        int selectedRow = viewappointmentTable.getSelectedRow();
        if (selectedRow != -1) {
            String appointmentId = viewappointmentTable.getModel().getValueAt(selectedRow, 0).toString();
            boolean success = customerService.cancelAppointment(appointmentId, customer);
            if (success) {
                CustomerClass psn = new CustomerClass(customer);
                psn.viewAppointment(viewappointmentTable, customer);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an appointment to cancel.");
        }
    }//GEN-LAST:event_cancelappointmentButtonActionPerformed

    private void viewappointmentTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewappointmentTableMouseReleased

    }//GEN-LAST:event_viewappointmentTableMouseReleased

    private void rescheduleappointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescheduleappointmentButtonActionPerformed
        int selectedRow = viewappointmentTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an appointment to reschedule.");
            return;
        }
        if (appointmemtDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a new date.");
            return;
        }
        if (timeComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a new time.");
            return;
        }
        String appointmentId = viewappointmentTable.getValueAt(selectedRow, 0).toString();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String newDate = dateFormat.format(appointmemtDateChooser.getDate());
        String newTime = timeComboBox.getSelectedItem().toString();
        boolean success = customerService.rescheduleAppointment(appointmentId, customer, newDate, newTime);
        if (success) {
            CustomerClass psn = new CustomerClass(customer);
            psn.viewAppointment(viewappointmentTable, customer);
            appointmemtDateChooser.setDate(null);
            timeComboBox.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_rescheduleappointmentButtonActionPerformed
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        int selectedRow = feedbackTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an appointment to comment on.");
            return;
        }
        String appointmentId = feedbackTable.getValueAt(selectedRow, 0).toString();
        String staffComment = staffTextField.getText().trim();
        String doctorComment = doctorTextField.getText().trim();
        boolean success = customerService.submitFeedback(appointmentId, customer, staffComment, doctorComment);
        if (success) {
            staffTextField.setText("");
            doctorTextField.setText("");
            customerService.loadFeedbackTable(feedbackTable, customer);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void showhistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showhistoryButtonActionPerformed
        int selectedRow = completeTable.getSelectedRow(); 
        if (selectedRow != -1) {
            String id = completeTable.getValueAt(selectedRow, 0).toString();
            String doctorName = completeTable.getValueAt(selectedRow, 1).toString();
            String doctorReview = completeTable.getValueAt(selectedRow, 2).toString();
            String ctoStaff = completeTable.getValueAt(selectedRow, 3).toString();
            String ctoDoctor = completeTable.getValueAt(selectedRow, 4).toString();
            String charges = completeTable.getValueAt(selectedRow, 5).toString();
            String date = completeTable.getValueAt(selectedRow, 6).toString();
            String time = completeTable.getValueAt(selectedRow, 7).toString();
            String status = completeTable.getValueAt(selectedRow, 8).toString();

            
            JOptionPane.showMessageDialog(null, "Appointment ID: " + id + "\n"
                    + "Doctor Name: " + doctorName + "\n"
                    + "Doctor Review: " + doctorReview + "\n"
                    + "Comment to staff: " + ctoStaff + "\n"
                    + "Comment to doctor: " + ctoDoctor + "\n"
                    + "Charges: " + charges + "\n"
                    + "Date: " + date + "  " + time + "\n"
                    + "Status: " + status, "Appointment Details", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Please select an appointment first!", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_showhistoryButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String newUsernameInput = this.newnameTextfield.getText().trim();
        String newPasswordInput = this.newpasswordTextfield.getText().trim();
        if(newUsernameInput.isEmpty()){
            newUsernameInput = customer.getUsername();
        }
        if(newPasswordInput.isEmpty()){
            newPasswordInput = customer.getPassword();
        }
        if (newUsernameInput.isEmpty() && newPasswordInput.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter new username and password");
            return;
        }        
        DoctorClass psn = new DoctorClass(customer);
        psn.editProfile(customer, newUsernameInput, newPasswordInput);
        this.remove(editProfilePanel);
        this.revalidate();
        this.repaint();
        Login user = new Login();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void newnameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newnameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newnameTextfieldActionPerformed

    private void newpasswordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordTextfieldActionPerformed

    private void appointmemtDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_appointmemtDateChooserPropertyChange
        CustomerClass.availableTime(timeComboBox, appointmemtDateChooser);
    }//GEN-LAST:event_appointmemtDateChooserPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Customer(new User()).setVisible(true));
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Customer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private com.toedter.calendar.JDateChooser appointmemtDateChooser;
    private javax.swing.JButton cancelappointmentButton;
    private javax.swing.JLabel ccdLabel;
    private javax.swing.JLabel ccsLabel;
    private javax.swing.JTable completeTable;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextField doctorTextField;
    private javax.swing.JPanel editProfilePanel;
    private javax.swing.JButton editprofileButton;
    private javax.swing.JButton epButton;
    private javax.swing.JTable feedbackTable;
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JLabel fullnamelabel;
    private javax.swing.JLabel fullnameuserLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JScrollPane historyScrollPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel iduserLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel nameuserLabel;
    private javax.swing.JLabel newnameLabel;
    private javax.swing.JTextField newnameTextfield;
    private javax.swing.JLabel newpasswordLabel;
    private javax.swing.JTextField newpasswordTextfield;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JLabel passworduserLabel;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton refreshhistoryButton;
    private javax.swing.JButton rescheduleappointmentButton;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel rolelabel;
    private javax.swing.JLabel roleuserLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton showhistoryButton;
    private javax.swing.JTextField staffTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel submitCommentPanel;
    private javax.swing.JButton submitcommentButton;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JLabel timeLable;
    private javax.swing.JLabel userfullnameLabel;
    private javax.swing.JLabel useridLabel;
    private javax.swing.JLabel userroleLabel;
    private javax.swing.JPanel viewAppointmentPanel;
    private javax.swing.JPanel viewHistoryPanel;
    private javax.swing.JPanel viewProfilePanel;
    private javax.swing.JButton viewappointmentButton;
    private javax.swing.JTable viewappointmentTable;
    private javax.swing.JButton viewhistoryButton;
    // End of variables declaration//GEN-END:variables

    private void initializeDateTimeOptions() {
        // Initialize time combo box with default options
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Select Time");
        timeComboBox.setModel(model);
        timeComboBox.setEnabled(false); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
